### ISSUE TITLE
Clarify relationship with @sandstreamdev/react-swipeable-list

### ISSUE THREAD

**Issue by alaycock** [marekrozmus/react-swipeable-list#6]
I'd appreciate it if the README of this repo could clarify the relationship between this and https://github.com/sandstreamdev/react-swipeable-list/

When I first found this repo, it had the features I wanted over the sandstreamdev version. Given the similarities of the README and the repo name, it was hard to tell the two repos apart. I didn't know which one was the original and which was the fork, if both projects are maintained, and which one I might want to use.

After looking at the history, this appears to be a fork. Given the very similar naming, I'd like to understand why you published this fork and the main differences from the sandstreamdev version. For example, is the `sandstreamdev` version no longer being maintained? This has more features, but do you intend to maintain alignment with bugfixes in standstreamdev, or is this a totally divergent fork?

**Comment by marekrozmus** [comment]
The story looks like this. I'm the author of both of them. I've implemented the sandstreamdev/react-swipeable-list/ some time ago at company I used to work. That version is around for some time and it looks like pretty stable.

I got several requests for making it work like on iOS but the problem was that I couldn't make it work with some minor changes and didn't want to break it 😉 

So when I finally got some free time I've implemented whole new version. I wanted it to follow compound component React pattern and implement all 3 behaviours I've seen so far for that kind of list. So you can say this one is fork but almost fully reimplmented ✨ 

As I'm not so great at generating some great name I left the old one but it is not scoped anymore.

I do not maintain the sandstreamdev/react-swipeable-list/ anymore as I don't have time and would like to focus on the new version. But you can ask there maybe some other mainteners would still fix some issues.

I'll write some short summary later in Readme. I hope that now you know why it all look this way. If something is still vague let me know - the more questions the better answer I can give 🙂

Thanks for your time!

**Comment by marekrozmus** [comment]
Thst does not mean that in this new version I didn't make some new bugs 😄 
Now working on typescript definitions as they are totally different than in sandstreamdev/react-swipeable-list/

Let me know if you need anything more in this component or think something should be changed to be more user friendly :)

I'd really like to see some demos what people are making with this component but no idea how to aproach to this topic. People make great designs - I don't 😉
